/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    icons: Icon;
    pages: Page;
    news: News;
    events: Event;
    angebote: Angebote;
    'signature-dishes': SignatureDish;
    stationen: Stationen;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    icons: IconsSelect<false> | IconsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    angebote: AngeboteSelect<false> | AngeboteSelect<true>;
    'signature-dishes': SignatureDishesSelect<false> | SignatureDishesSelect<true>;
    stationen: StationenSelect<false> | StationenSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Beschreibt das Bild für Screenreader und Suchmaschinen.
   */
  alt: string;
  kategorie?:
    | (
        | 'portraet'
        | 'gerichte'
        | 'kueche'
        | 'team'
        | 'stationen'
        | 'location'
        | 'event'
        | 'publikation'
        | 'hobby'
        | 'privat'
      )
    | null;
  /**
   * Nur für Bilder der Kategorie «Hobby».
   */
  hobby?:
    | (
        | 'biken'
        | 'garten'
        | 'pfadfinder'
        | 'outdoor-kochen'
        | 'backen'
        | 'skitouren'
        | 'trailrunning'
        | 'yoga'
        | 'reisen'
      )
    | null;
  /**
   * Sichtbarer Text unter dem Bild, sofern die Seite eine Legende zeigt.
   */
  caption?: string | null;
  /**
   * Aufnahmejahr, sofern bekannt.
   */
  jahr?: number | null;
  verwendung?: ('web' | 'intern' | 'archiv') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "icons".
 */
export interface Icon {
  id: number;
  /**
   * Eindeutiger Name, z.B. «map-pin» oder «instagram»
   */
  name: string;
  /**
   * Inline-SVG für das Frontend (nutzt currentColor). Wird beim Seed aus der Datei übernommen.
   */
  svg?: string | null;
  /**
   * Sprüche, die beim Anklicken des Icons erscheinen. Icons mit Sprüchen zählen als entdeckbare «Zutat». Mehrere Sprüche wechseln sich bei wiederholtem Klick ab.
   */
  toasts?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * «home» für die Startseite
   */
  slug: string;
  sections?:
    | (
        | {
            anchor?: string | null;
            eyebrow?: string | null;
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            quote?: string | null;
            quoteSource?: string | null;
            image?: (number | null) | Media;
            values?:
              | {
                  icon?: (number | null) | Icon;
                  title: string;
                  text?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'philosophie';
          }
        | {
            anchor?: string | null;
            eyebrow?: string | null;
            heading: string;
            intro?: string | null;
            angebote?: (number | Angebote)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'angeboteSection';
          }
        | {
            anchor?: string | null;
            eyebrow?: string | null;
            heading: string;
            intro?: string | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'eventsSection';
          }
        | {
            anchor?: string | null;
            eyebrow?: string | null;
            heading: string;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsSection';
          }
        | {
            anchor?: string | null;
            eyebrow?: string | null;
            heading: string;
            intro?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'signatureDishesSection';
          }
        | {
            anchor?: string | null;
            eyebrow?: string | null;
            heading: string;
            intro?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stationenSection';
          }
        | {
            anchor?: string | null;
            eyebrow?: string | null;
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            image?: (number | null) | Media;
            mapEmbedUrl?: string | null;
            infos?:
              | {
                  icon?: (number | null) | Icon;
                  label: string;
                  value: string;
                  url?: string | null;
                  id?: string | null;
                }[]
              | null;
            cta?: {
              label?: string | null;
              url?: string | null;
            };
            secondaryCta?: {
              label?: string | null;
              url?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'visitSection';
          }
        | {
            anchor?: string | null;
            heading?: string | null;
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richTextSection';
          }
      )[]
    | null;
  seo?: {
    /**
     * Leer lassen für Standard aus Site-Einstellungen
     */
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "angebote".
 */
export interface Angebote {
  id: number;
  title: string;
  /**
   * Der Teil der Adresse nach dem Sammlungsnamen. Wird beim Anlegen aus dem Titel gebildet und danach nicht mehr geändert — ein neuer Slug bricht geteilte Links.
   */
  slug: string;
  eyebrow?: string | null;
  /**
   * Icon für Karten-/Tab-Darstellung
   */
  icon?: (number | null) | Icon;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  features?:
    | {
        icon?: (number | null) | Icon;
        text: string;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  cta?: {
    label?: string | null;
    url?: string | null;
  };
  /**
   * Kleiner heisst weiter vorn. Neue Einträge kommen von selbst nach hinten.
   */
  order?: number | null;
  seo?: {
    /**
     * Leer lassen für Standard aus Site-Einstellungen
     */
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  date: string;
  badge?: string | null;
  excerpt: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  link?: {
    label?: string | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * Der Teil der Adresse nach dem Sammlungsnamen. Wird beim Anlegen aus dem Titel gebildet und danach nicht mehr geändert — ein neuer Slug bricht geteilte Links.
   */
  slug: string;
  rhythmus: 'einmalig' | 'woechentlich';
  /**
   * Bestimmt die Anzeige und das Termin-Schema für Google.
   */
  wochentag?: ('Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday') | null;
  /**
   * Bei einem einzelnen Termin das Datum. Bei einem wöchentlichen Anlass der Beginn der Reihe — er bleibt danach stehen.
   */
  datum?: string | null;
  /**
   * Als «18:00». Wird so angezeigt und ins Schema übernommen.
   */
  zeit?: string | null;
  eyebrow?: string | null;
  icon?: (number | null) | Icon;
  excerpt: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional. Wechselt beim Gourmetabend wöchentlich.
   */
  menu?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * z.B. «CHF 98»
   */
  preis?: string | null;
  ort?: string | null;
  image?: (number | null) | Media;
  cta?: {
    label?: string | null;
    url?: string | null;
  };
  seo?: {
    /**
     * Leer lassen für Standard aus Site-Einstellungen
     */
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signature-dishes".
 */
export interface SignatureDish {
  id: number;
  name: string;
  tag?: string | null;
  icon?: (number | null) | Icon;
  description?: string | null;
  image?: (number | null) | Media;
  videoUrl?: string | null;
  /**
   * Kleiner heisst weiter vorn. Neue Einträge kommen von selbst nach hinten.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stationen".
 */
export interface Stationen {
  id: number;
  group: 'stationen' | 'ausbildung' | 'qualifikationen' | 'hobbies';
  /**
   * z.B. «2019 – 2023»
   */
  period?: string | null;
  title: string;
  place?: string | null;
  description?: string | null;
  icon?: (number | null) | Icon;
  highlights?:
    | {
        icon?: (number | null) | Icon;
        text: string;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  /**
   * Kleiner heisst weiter vorn. Neue Einträge kommen von selbst nach hinten.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  pages?: {
    /**
     * Allow clients to find pages.
     */
    find?: boolean | null;
    /**
     * Allow clients to create pages.
     */
    create?: boolean | null;
    /**
     * Allow clients to update pages.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete pages.
     */
    delete?: boolean | null;
  };
  news?: {
    /**
     * Allow clients to find news.
     */
    find?: boolean | null;
    /**
     * Allow clients to create news.
     */
    create?: boolean | null;
    /**
     * Allow clients to update news.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete news.
     */
    delete?: boolean | null;
  };
  events?: {
    /**
     * Allow clients to find events.
     */
    find?: boolean | null;
    /**
     * Allow clients to create events.
     */
    create?: boolean | null;
    /**
     * Allow clients to update events.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete events.
     */
    delete?: boolean | null;
  };
  angebote?: {
    /**
     * Allow clients to find angebote.
     */
    find?: boolean | null;
    /**
     * Allow clients to create angebote.
     */
    create?: boolean | null;
    /**
     * Allow clients to update angebote.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete angebote.
     */
    delete?: boolean | null;
  };
  signatureDishes?: {
    /**
     * Allow clients to find signature-dishes.
     */
    find?: boolean | null;
    /**
     * Allow clients to create signature-dishes.
     */
    create?: boolean | null;
    /**
     * Allow clients to update signature-dishes.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete signature-dishes.
     */
    delete?: boolean | null;
  };
  stationen?: {
    /**
     * Allow clients to find stationen.
     */
    find?: boolean | null;
    /**
     * Allow clients to create stationen.
     */
    create?: boolean | null;
    /**
     * Allow clients to update stationen.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete stationen.
     */
    delete?: boolean | null;
  };
  icons?: {
    /**
     * Allow clients to find icons.
     */
    find?: boolean | null;
    /**
     * Allow clients to create icons.
     */
    create?: boolean | null;
    /**
     * Allow clients to update icons.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete icons.
     */
    delete?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
    /**
     * Allow clients to create media.
     */
    create?: boolean | null;
    /**
     * Allow clients to update media.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete media.
     */
    delete?: boolean | null;
  };
  header?: {
    /**
     * Allow clients to find header global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update header global.
     */
    update?: boolean | null;
  };
  footer?: {
    /**
     * Allow clients to find footer global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update footer global.
     */
    update?: boolean | null;
  };
  siteSettings?: {
    /**
     * Allow clients to find site-settings global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update site-settings global.
     */
    update?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'icons';
        value: number | Icon;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'angebote';
        value: number | Angebote;
      } | null)
    | ({
        relationTo: 'signature-dishes';
        value: number | SignatureDish;
      } | null)
    | ({
        relationTo: 'stationen';
        value: number | Stationen;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  kategorie?: T;
  hobby?: T;
  caption?: T;
  jahr?: T;
  verwendung?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "icons_select".
 */
export interface IconsSelect<T extends boolean = true> {
  name?: T;
  svg?: T;
  toasts?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  sections?:
    | T
    | {
        philosophie?:
          | T
          | {
              anchor?: T;
              eyebrow?: T;
              heading?: T;
              body?: T;
              quote?: T;
              quoteSource?: T;
              image?: T;
              values?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        angeboteSection?:
          | T
          | {
              anchor?: T;
              eyebrow?: T;
              heading?: T;
              intro?: T;
              angebote?: T;
              id?: T;
              blockName?: T;
            };
        eventsSection?:
          | T
          | {
              anchor?: T;
              eyebrow?: T;
              heading?: T;
              intro?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        newsSection?:
          | T
          | {
              anchor?: T;
              eyebrow?: T;
              heading?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        signatureDishesSection?:
          | T
          | {
              anchor?: T;
              eyebrow?: T;
              heading?: T;
              intro?: T;
              id?: T;
              blockName?: T;
            };
        stationenSection?:
          | T
          | {
              anchor?: T;
              eyebrow?: T;
              heading?: T;
              intro?: T;
              id?: T;
              blockName?: T;
            };
        visitSection?:
          | T
          | {
              anchor?: T;
              eyebrow?: T;
              heading?: T;
              body?: T;
              image?: T;
              mapEmbedUrl?: T;
              infos?:
                | T
                | {
                    icon?: T;
                    label?: T;
                    value?: T;
                    url?: T;
                    id?: T;
                  };
              cta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richTextSection?:
          | T
          | {
              anchor?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  badge?: T;
  excerpt?: T;
  body?: T;
  image?: T;
  link?:
    | T
    | {
        label?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  rhythmus?: T;
  wochentag?: T;
  datum?: T;
  zeit?: T;
  eyebrow?: T;
  icon?: T;
  excerpt?: T;
  body?: T;
  menu?:
    | T
    | {
        text?: T;
        id?: T;
      };
  preis?: T;
  ort?: T;
  image?: T;
  cta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "angebote_select".
 */
export interface AngeboteSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  eyebrow?: T;
  icon?: T;
  description?: T;
  features?:
    | T
    | {
        icon?: T;
        text?: T;
        id?: T;
      };
  image?: T;
  cta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  order?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signature-dishes_select".
 */
export interface SignatureDishesSelect<T extends boolean = true> {
  name?: T;
  tag?: T;
  icon?: T;
  description?: T;
  image?: T;
  videoUrl?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stationen_select".
 */
export interface StationenSelect<T extends boolean = true> {
  group?: T;
  period?: T;
  title?: T;
  place?: T;
  description?: T;
  icon?: T;
  highlights?:
    | T
    | {
        icon?: T;
        text?: T;
        id?: T;
      };
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  pages?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  news?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  events?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  angebote?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  signatureDishes?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  stationen?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  icons?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  media?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  header?:
    | T
    | {
        find?: T;
        update?: T;
      };
  footer?:
    | T
    | {
        find?: T;
        update?: T;
      };
  siteSettings?:
    | T
    | {
        find?: T;
        update?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo?: {
    text?: string | null;
    image?: (number | null) | Media;
  };
  nav?:
    | {
        label: string;
        linkType?: ('anchor' | 'page' | 'url') | null;
        anchor?: string | null;
        page?: (number | null) | Page;
        url?: string | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    url?: string | null;
    icon?: (number | null) | Icon;
  };
  stage: {
    eyebrow?: string | null;
    headline: string;
    subline?: string | null;
    badges?:
      | {
          icon?: (number | null) | Icon;
          label: string;
          id?: string | null;
        }[]
      | null;
    image?: (number | null) | Media;
    videoUrl?: string | null;
    primaryCta?: {
      label?: string | null;
      url?: string | null;
    };
    secondaryCta?: {
      label?: string | null;
      url?: string | null;
    };
    scrollHint?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  about?: string | null;
  contact?: {
    address?: string | null;
    phone?: string | null;
    email?: string | null;
  };
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              linkType?: ('anchor' | 'page' | 'url') | null;
              anchor?: string | null;
              page?: (number | null) | Page;
              url?: string | null;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  socials?:
    | {
        icon?: (number | null) | Media;
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        linkType?: ('anchor' | 'page' | 'url') | null;
        anchor?: string | null;
        page?: (number | null) | Page;
        url?: string | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  domain?: string | null;
  defaultSeo?: {
    title?: string | null;
    /**
     * z.B. «%s | Sebastian Titz»
     */
    titleTemplate?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  easterEggs?: {
    completionToast?: string | null;
    starToast?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?:
    | T
    | {
        text?: T;
        image?: T;
      };
  nav?:
    | T
    | {
        label?: T;
        linkType?: T;
        anchor?: T;
        page?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        url?: T;
        icon?: T;
      };
  stage?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        subline?: T;
        badges?:
          | T
          | {
              icon?: T;
              label?: T;
              id?: T;
            };
        image?: T;
        videoUrl?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              url?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              url?: T;
            };
        scrollHint?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  about?: T;
  contact?:
    | T
    | {
        address?: T;
        phone?: T;
        email?: T;
      };
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              linkType?: T;
              anchor?: T;
              page?: T;
              url?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  socials?:
    | T
    | {
        icon?: T;
        label?: T;
        url?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        linkType?: T;
        anchor?: T;
        page?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  domain?: T;
  defaultSeo?:
    | T
    | {
        title?: T;
        titleTemplate?: T;
        description?: T;
        image?: T;
      };
  easterEggs?:
    | T
    | {
        completionToast?: T;
        starToast?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}